---
title: "PCA"
output:
  html_document:
    df_print: paged
---

https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

```{r}
library(readr)
EZ_Batch1 <- read_csv("step\ 1/EZ_Batch1.csv")
EZ_Batch1<-as.data.frame(EZ_Batch1)


```
```{r}
head(EZ_Batch1)
```


```{r}
library(Seurat)
```
```{r}
colnames(EZ_Batch1)[1] <- "gene"
rownames(EZ_Batch1) <- EZ_Batch1$gene
EZ_Batch1$gene <- NULL
head(EZ_Batch1)

```


```{r}
obj <- CreateSeuratObject(counts=EZ_Batch1, project="EZ_Batch1", min.cells = 3, min.features = 200)
obj
```
```{r}
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")
```

```{r}
obj <- subset(obj, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
obj <- NormalizeData(obj, normalization.method = "LogNormalize", scale.factor = 10000)
```
```{r}
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000)
```
```{r}
all.genes <- rownames(obj)
obj <- ScaleData(obj, features = all.genes)
```
```{r}
obj <- RunPCA(obj, features = VariableFeatures(object = obj))
print(obj[["pca"]], dims = 1:5, nfeatures = 5)
```


```{r}
obj <- FindNeighbors(obj, dims = 1:20)
obj <- FindClusters(obj, resolution = 0.5)
```




```{r}
obj <- RunUMAP(obj, dims = 1:20)
DimPlot(obj, reduction = "umap", label=TRUE)
```

```{r}
c_1 <- subset(obj, idents = c("1"))
```

```{r}
saveRDS(c_1, file = "c1.rds")
```